name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@master
      with:
        token: ${{ secrets.METRICS_SECRET }}
    - name: Update with latest blog posts
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Get RSS Feed
          uses: kohrongying/readme-the-rss@master
          with:
            feed_url: https://mijndertstuij.nl/feed.xml
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi